server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://core-db:5432/core_services?currentSchema=compilation_service
    username: dbuser
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      default_schema: compilation_service   # <-- добавлено
    show-sql: false

logging:
  level:
    ru.practicum: DEBUG