server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: admin-users-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/admin/users/**
        - id: admin-events-route
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/admin/events/**
        - id: admin-categories-route
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/admin/categories/**
        - id: admin-compilations-route
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/admin/compilations/**
        - id: admin-comments-route
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/admin/reviews/**
        - id: private-requests-route
          uri: lb://REQUEST-SERVICE
          predicates:
            - Path=/users/*/requests/**
        - id: private-events-route
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/users/*/events/**
        - id: private-comments-route
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/users/*/reviews/**
        - id: public-categories-route
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/categories/**
        - id: public-compilations-route
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/compilations/**
        - id: public-events-route
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/events/**
        - id: public-comments-route
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/reviews/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,gateway