server:
  port: 0

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.time_zone: UTC
        format_sql: true
    show-sql: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://stats-db:5432/analyzerdb}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:dbuser}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}

grpc:
  server:
    port: 0

analyzer:
  kafka-consumer-actions:
    properties:
      bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: ru.practicum.avro.deserializer.UserActionDeserializer
      client.id: analyzer
      group.id: analyzer-actions-group
      enable.auto.commit: false
    topic: stats.user-actions.v1
    timeout: 10000
  kafka-consumer-similarity:
    properties:
      bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: ru.practicum.avro.deserializer.EventSimilarityDeserializer
      client.id: analyzer
      group.id: analyzer-similarity-group
      enable.auto.commit: false
    topic: stats.events-similarity.v1
    timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info
  endpoint:
    health:
      show-details: always