spring:
  application:
    name: main-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 10
        max-interval: 3000
  config:
    import: "configserver:"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/